-- 1. Crear la Base de Datos
CREATE DATABASE BD_TRANSACCIONES_OMM;
GO

USE BD_TRANSACCIONES_OMM;
GO

-- 2. Crear Tabla CUENTA
CREATE TABLE CUENTA (
    NRO_CUENTA NVARCHAR(14) NOT NULL,
    TIPO CHAR(3) NOT NULL, -- AHO o CTE
    MONEDA CHAR(3) NOT NULL, -- BOL o USD
    NOMBRE NVARCHAR(40) NOT NULL,
    SALDO DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    CONSTRAINT PK_CUENTA PRIMARY KEY (NRO_CUENTA),
    CONSTRAINT CHK_TIPO CHECK (TIPO IN ('AHO', 'CTE'))
);
GO

-- 3. Crear Tabla MOVIMIENTO
CREATE TABLE MOVIMIENTO (
    NRO_CUENTA NVARCHAR(14) NOT NULL,
    FECHA DATETIME NOT NULL DEFAULT GETDATE(),
    TIPO CHAR(1) NOT NULL, -- D (Debito/Retiro) o A (Abono/Deposito)
    IMPORTE DECIMAL(12,2) NOT NULL,
    CONSTRAINT PK_MOVIMIENTO PRIMARY KEY (NRO_CUENTA, FECHA),
    CONSTRAINT FK_MOVIMIENTO_CUENTA FOREIGN KEY (NRO_CUENTA) REFERENCES CUENTA(NRO_CUENTA),
    CONSTRAINT CHK_TIPO_MOV CHECK (TIPO IN ('D', 'A'))
);
GO

-- 4. Crear Usuario de Base de Datos (Segun requerimiento IV.2)
-- Primero creamos el Login en el servidor
CREATE LOGIN USUARIO_OMM WITH PASSWORD = 'PASSWORD_OMM';
GO

-- Luego creamos el Usuario en la base de datos y le asignamos el rol dbo
CREATE USER USUARIO FOR LOGIN USUARIO;
GO

ALTER ROLE db_owner ADD MEMBER USUARIO;
GO
