CREATE TABLE CUENTA (
	NRO_CUENTA NVARCHAR(14) NOT NULL,
	TIPO CHAR(3) NOT NULL,
	MONEDA CHAR(3) NOT NULL,
	NOMBRE NVARCHAR(40) NOT NULL,
	SALDO DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
	CONSTRAINT PK_CUENTA PRIMARY KEY (NRO_CUENTA),
	CONSTRAINT CHK_TIPO CHECK (TIPO IN ('AHO','CTE'))
);

CREATE TABLE MOVIMIENTO (
	NRO_CUENTA NVARCHAR(14) NOT NULL,
	FECHA DATETIME NOT NULL DEFAULT GETDATE(),
	TIPO CHAR(1) NOT NULL,
	IMPORTE DECIMAL(12,2) NOT NULL DEFAULT 0.00,

	CONSTRAINT PK_MOVIMIENTO PRIMARY KEY (NRO_CUENTA, FECHA),
	CONSTRAINT CHK_TIPO_MOV CHECK (TIPO IN ('D', 'A')),

	CONSTRAINT FK_MOVIMIENTO_CUENTA FOREIGN KEY (NRO_CUENTA) REFERENCES CUENTA(NRO_CUENTA)
);

CREATE LOGIN USUARIO_OMM WITH PASSWORD = 'PASSWORD_OMM';

CREATE USER USUARIO_OMM FOR LOGIN USUARIO_OMM;
ALTER ROLE db_owner ADD MEMBER USUARIO_OMM;

-- agregar cuentas
USE BD_TRANSACCIONES_OMM;
GO

CREATE PROCEDURE sp_RegistrarCuenta
	@NroCuenta NVARCHAR(14),
    @Tipo CHAR(3),
    @Moneda CHAR(3),
    @Nombre NVARCHAR(40)
AS
BEGIN
	-- El saldo inicial siempre es 0 según el requerimiento
	INSERT INTO CUENTA (NRO_CUENTA, TIPO, MONEDA, NOMBRE, SALDO)
	VALUES (@NroCuenta, @Tipo, @Moneda, @Nombre, 0.00);
END
GO





----------------------------------
CREATE DATABASE BD_TRANSACCIONES_OMM_NEW;

USE BD_TRANSACCIONES_OMM_NEW;

CREATE LOGIN USUARIO WITH PASSWORD = 'PASSWORD';
CREATE USER USUARIO FOR LOGIN USUARIO;
ALTER ROLE db_owner ADD MEMBER USUARIO;

CREATE TABLE moneda (
    codigo CHAR(3) PRIMARY KEY,
    nombre NVARCHAR(50) NOT NULL,
    simbolo NVARCHAR(5)
);

CREATE TABLE cuenta (
    nro_cuenta NVARCHAR(14) PRIMARY KEY,
    tipo CHAR(3) CHECK (TIPO IN ('AHO', 'CTE')),
    moneda CHAR(3),
    nombre NVARCHAR(40),
    saldo DECIMAL(12, 2)
	CONSTRAINT FK_CUENTA_MONEDA FOREIGN KEY (moneda) REFERENCES moneda(codigo),
);

CREATE TABLE movimiento (
	fecha DATETIME2 PRIMARY KEY,
	tipo char(1) CHECK (TIPO IN ('D', 'A')),
	importe decimal(12,2),
	nro_cuenta NVARCHAR(14),
	CONSTRAINT FK_MOVIMEINTO_CUENTA FOREIGN KEY (nro_cuenta) REFERENCES cuenta(nro_cuenta),
);

CREATE TABLE tipo_cambio (
    id INT IDENTITY(1,1) PRIMARY KEY,
    fecha DATE NOT NULL,
    moneda_origen CHAR(3) NOT NULL,
    moneda_destino CHAR(3) NOT NULL,
    tasa DECIMAL(10, 6) NOT NULL,
    CONSTRAINT FK_TIPO_CAMBIO_MONEDA_ORIGEN FOREIGN KEY (moneda_origen) REFERENCES moneda(codigo),
    CONSTRAINT FK_TIPO_CAMBIO_MONEDA_DESTINO FOREIGN KEY (moneda_destino) REFERENCES moneda(codigo)
);